"""fixing some problems

Revision ID: f6d560688a8e
Revises: e356a59953b2
Create Date: 2026-02-03 14:01:09.005646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d560688a8e'
down_revision: Union[str, Sequence[str], None] = 'e356a59953b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('org_level', sa.String(), nullable=True))
    op.add_column('users', sa.Column('hire_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hire_date')
    op.drop_column('users', 'org_level')
    # ### end Alembic commands ###
